* MediaIndexer

** Synopsis
** Installation

   If [[https://hex.pm/docs/publish][available in Hex]], the package can be
   installed by adding =media_indexer= to your list of dependencies in
   =mix.exs=:

   #+BEGIN_EXAMPLE elixir
    def deps do
      [
        {:media_indexer, "~> 0.1.0"}
      ]
    end
   #+END_EXAMPLE

   Documentation can be generated with
   [[https://github.com/elixir-lang/ex_doc][ExDoc]] and published on
   [[https://hexdocs.pm][HexDocs]]. Once published, the docs can be found
   at [[https://hexdocs.pm/media_indexer]].

** Notes
*** Building and interacting with the project
    #+begin_src bash
    mix escript.build
    #+end_src

    Emacs development string
    #+begin_src bash
    cd /development/elixir_proj/media_indexer ; LC_ALL=de_DE.UTF-8 mix escript.build
    #+end_src

    Observer
    #+begin_src elixir
    :observer.start
    #+end_src
*** Configuration
**** Copied from the config file template
     This configuration is loaded before any dependency and is restricted
     to this project. If another project depends on this project, this
     file won't be loaded nor affect the parent project. For this reason,
     if you want to provide default values for your application for
     3rd-party users, it should be done in your "mix.exs" file.

     You can configure your application as:
    
     #+begin_src elixir
     config :media_indexer, key: :value
     #+end_src

     and access this configuration in your application as:

     #+begin_src elixir
     Application.get_env(:media_indexer, :key)
     #+end_src
     
     You can also configure a 3rd-party app:

     #+begin_src elixir
     config :logger, level: :info
     #+end_src

     It is also possible to import configuration files, relative to this
     directory. For example, you can emulate configuration per environment
     by uncommenting the line below and defining dev.exs, test.exs and such.
     Configuration from the imported file will override the ones defined
     here (which is why it is important to import them last).

     #+begin_src elixir
     import_config "#{Mix.env}.exs"
     #+end_src
